export const IpcChannels = {
  settingsGet: 'albert:settings:get',
  settingsSet: 'albert:settings:set',
  chatSend: 'albert:chat:send',
  chatHistory: 'albert:chat:history',
  chatClear: 'albert:chat:clear',
  chatAppend: 'albert:chat:append',
  chatImageData: 'albert:chat:image-data',
  memoryList: 'albert:memory:list',
  memoryDelete: 'albert:memory:delete',
  memoryUpdate: 'albert:memory:update',
  activityList: 'albert:activity:list',
  activityClear: 'albert:activity:clear',
  realtimeSession: 'albert:realtime:session',
  toolExecute: 'albert:tool:execute',
  windowToggle: 'albert:window:toggle',
  windowHide: 'albert:window:hide',
  windowShow: 'albert:window:show',
  openPrivacyPane: 'albert:system:open-privacy',
  ollamaProbe: 'albert:ollama:probe',
  groqProbe: 'albert:groq:probe',
  voiceWarm: 'albert:voice:warm',
  voiceTranscribe: 'albert:voice:transcribe',
  companionStatus: 'albert:companion:status',
  companionApply: 'albert:companion:apply',
  companionRotateToken: 'albert:companion:rotate-token',
  ttsSpeak: 'albert:tts:speak',
  ttsKokoro: 'albert:tts:kokoro',
  ttsKokoroWarm: 'albert:tts:kokoro-warm',
  ttsKokoroProgress: 'albert:tts:kokoro-progress',
  computerState: 'albert:computer:state',
  computerShow: 'albert:computer:show',
  computerOpen: 'albert:computer:open',
  computerNavigate: 'albert:computer:navigate',
  computerFocus: 'albert:computer:focus',
  computerClose: 'albert:computer:close',
  computerUpdateTab: 'albert:computer:update-tab',
  computerGetPage: 'albert:computer:get-page'
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
